# Generated by Django 5.0.6 on 2024-06-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0010_alter_customer_options_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can Cancel Order')]},
        ),
    ]
